version: "3.1"

services:
  spk_cli:
    image: mkenjis/ubspkcluster1_s3_img
    environment:
      - HADOOP_HOSTNAME=hdpmst
    networks:
      - mynet
    depends_on:
      - hdpmst
  hdpmst:
    image: mkenjis/ubhdpclu_img
    networks:
      - mynet
    environments:
      - HADOOP_HOST_SLAVES=hdp1,hdp2,hdp3
    depends_on:
      - hdp1,hdp2,hdp3
  hdp1:
    image: mkenjis/ubhdpclu_img
    networks:
      - mynet
  hdp2:
    image: mkenjis/ubhdpclu_img
    networks:
      - mynet
  hdp3:
    image: mkenjis/ubhdpclu_img
    networks:
      - mynet

networks:
  mynet: